### ISSUE TITLE
setTimeout issue with roles

### ISSUE THREAD

**Issue by hassanasad** [jalik/jalik-roles#1]
Hi,

I am using this package with flow-router 2.0
The issue i am facing is that in the client files (like client.js in client folder) if i do this:

``` javascript
console.log(Roles.userCan('administrate'));
```

It prints false

However, if i do this:

``` javascript
setTimeout( function() {
    console.log(Roles.userCan('administrate'));
}, 1447);
```

It prints true.

That value 1447 is the least value i need to set before it returns true (which it should as user is assigned that role).

Can you please let me know if i am doing something wrong.

I am using Meteor 1.1.0.2 and the latest version of your package.

**Comment by jalik** [comment]
Hi @hassanasad, the Roles.userCan() works like Meteor.user() in the way that it is reactive.
If you refresh the page, it will load userId, user object, roleId and role object, but they won't be all available in one shot as you obtain them with an automatic subscription.

If you want to execute the permission only when the role is loaded on the client you should do that :

``` js
if (Meteor.role() && Roles.userCan('do something')) {
    console.log('user can do something');
}
```

I could add a method Roles.ready() that would do the same for convenience :

``` js
Roles.ready = function() {
    // undefined means that we don't have loaded the role yet
    return Meteor.role() !== undefined;
}
```

**Comment by hassanasad** [comment]
Thanks Jalik for the explanation of the issue. I understand it.

What i am trying to do is use Flow-router 2.0 from kadira. I want to allow certain links for certain user roles. For example, i want only 'administrators' to be able to access /dashabord/ URLs. Is there a neater way to do this?

My current code is like this:

``` javascript
var adminRoutes = FlowRouter.group({
    prefix: '/dashboard',
    triggersEnter: [function(context, redirect) {
        setTimeout( function() {
            if ( Meteor.isClient && Meteor.userId() ) {
                // User is logged in and is on client side
                if ( Roles.userCan('administrate') == true ) {
                    // User has access to view dashboard
                    BlazeLayout.render('backend', {main_template: "backend_home", sidebar_template: "backend_sidebar"});
                }
            } else {
                FlowRouter.go('/');
            }
        }, 1447);
    }]
});


adminRoutes.route('/', {
    action: function() {
        BlazeLayout.render('backend', {main_template: "backend_home", sidebar_template: "backend_sidebar"});
    }
});
```

Do you suggest that i use a setInterval and then check if Meteor.role() has been loaded and then try to use the condition Roles.userCan() ?

**Comment by jalik** [comment]
Hi @hassanasad, I know FlowRouter only by it's name so I can't help you with it, but I can tell you that you don't need to use timers or intervals, as the Roles.userCan() is reactive it will be called when permissions are loaded (until there is actually a bug).

So **remove** the `setTimeout()` because it's the wrong way..

I am using this kind of filter in IronRouter routes to display login form if user is trying to access admin area and it works so I don't see why it would not with FlowRouter.

There is also a `{{userCan 'administrate'}}` template helper that you can use directly inside templates if it can help you to display links.

**Comment by hassanasad** [comment]
When i remove `setTimeout` i get a boolean value of `false` for `Roles.userCan('administrate')` (even though the user i am checking has the permission `administrate`). However when i use the `setTimeout` with that value (or higher) i get the boolean value `true`.

I so want to remove the `setTimeout()` my self but can't think of an alternate.

Just to summarize what i mean, if i remove the `setTimeout()` i always get a boolean value of `false` so the condition fails.

Thanks for trying to debug this issue :smile:

**Comment by hassanasad** [comment]
Yes the template helpers work but i want to limit access based on the URLs too.

**Comment by jalik** [comment]
Okay, that's strange, have you tried that ?

``` js
if ( Meteor.isClient && Meteor.userId() && Meteor.role() ) {
    // ...
}
```

**Comment by hassanasad** [comment]
I just tried it

Didn't help either.

I currently have autopublish added. (however removing it doesn't make any difference either)

**Comment by jalik** [comment]
Let me some time to check this out, I will come back to you in the next 24 hours.

**Comment by hassanasad** [comment]
Ok i have noticed one thing.

it works this way

``` javascript
    if ( Meteor.isClient && Meteor.userId() && Meteor.role() ) {
        // User is logged in and is on client side
        if ( Roles.userCan('administrate') == true ) {
            // User has access to view dashboard
            BlazeLayout.render('backend', {main_template: "backend_home", sidebar_template: "backend_sidebar"});
        } else {
            FlowRouter.go('/');
        }
    } 
```

and _NOT_ this way:

``` javascript
    if ( Meteor.isClient && Meteor.userId() && Meteor.role() ) {
        // User is logged in and is on client side
        if ( Roles.userCan('administrate') == true ) {
            // User has access to view dashboard
            BlazeLayout.render('backend', {main_template: "backend_home", sidebar_template: "backend_sidebar"});
        }
    } else {
       FlowRouter.go('/');
    }
```

But now how do i send the user to '/' if he is not logged in ?

**Comment by hassanasad** [comment]
If i write:

``` javascript
console.log(Meteor.isClient);
console.log(Meteor.userId());
console.log(Meteor.role());
```

I get:

``` javascript
true
hFFzRLvrZyYFF7WHd
undefined
```

Which means (as you stated in the first reply) that at the time of checking of roles system, the value is not yet set.

**Comment by jalik** [comment]
What about :

``` js
    if ( Meteor.isClient ) {
        if ( Meteor.userId() && Meteor.role() ) {
            // User is logged in and is on client side
            if ( Roles.userCan('administrate') == true ) {
                // User has access to view dashboard
                BlazeLayout.render('backend', {main_template: "backend_home", sidebar_template: "backend_sidebar"});
            } else {
                FlowRouter.go('/');
            }
        }
    } 
```

**Comment by hassanasad** [comment]
Still the same. The condition is never true.

``` javascript
            if ( Meteor.isClient ) {
                if ( Meteor.userId() && Meteor.role() ) {
                    console.log(Meteor.role());
                    // DOESN'T COME HERE because Meteor.role is undefined
                    // User is logged in and is on client side
                    if ( Roles.userCan('administrate') == true ) {
                        // User has access to view dashboard
                        BlazeLayout.render('backend', {main_template: "backend_home", sidebar_template: "backend_sidebar"});
                    } else {
                        FlowRouter.go('/');
                    }
                }
            }
```

This code doesn't go in the condition because Meteor.role() always returns `undefined` even if i do it from browser console.

**Comment by jalik** [comment]
One thing is sure, you should only redirect user when role is loaded and the permissions failed.
If the test is executed before the role is loaded it redirects to the other route, then it will never enter the `Roles.userCan('administrate') == true` condition.

Globally, prefer rendering another template (like login) instead of redirecting.

**Comment by hassanasad** [comment]
Ok Jalik, thanks for helping out.

This method **works** as intended (however it uses `setInterval` which of course is not one of the best methods):

``` javascript
        if ( Meteor.isClient && Meteor.userId() ) {
            // Only do this on client side and for logged in users
            var interval = setInterval( function() {
                console.log('Roles are NOT loaded');
                if ( Meteor.role() != 'undefined' ) {
                    console.log('Roles are loaded');
                    clearInterval(interval);
                    // User is logged in and is on client side
                    if ( Roles.userCan('administrate') == true ) {
                        // User has access to view dashboard
                        BlazeLayout.render('backend', {main_template: "backend_home", sidebar_template: "backend_sidebar"});
                    } else {
                        // User doesn't have permission
                        FlowRouter.go('/');
                    }
                }
            }, 500);
        } else {
            // User not logged in - send back to home
            FlowRouter.go('/');
        }
```

It prints:

``` javascript
Roles are NOT loaded
Roles are loaded
```

**Comment by jalik** [comment]
Prefer `Meteor.setInterval` and `Meteor.clearInterval` instead of classic ones, it is recommended in the official doc.

You can remove `== true` after userCan() to simplify your code as the returned value is always boolean.

I still think that `if ( Meteor.isClient && Meteor.userId() ) {`
could be executed before the userId is loaded, this will then redirect to '/', and this is not what you want, or maybe I don't understand your code..

**Comment by hassanasad** [comment]
Ah - thanks for the `Meteor.setInterval` and `Meteor.clearInterval`

According to my tests so far (which are on my local machine) `Meteor.userId()` is loaded and available at the time when its called. Will need to deploy it on live to see if this behavior changes.

The code i posted previously works but that requires me to use setIntervals every place where i need to actually route. That is not a good approach :cry: 

Is there any way to pre-load some function (along with their values) before Meteor JS files are processed?

**Comment by jalik** [comment]
I don't think there is a solution to preload data from subscriptions and routing with permissions is something not that easy actually...

**Comment by jalik** [comment]
Could you test with the latest release **v0.1.2** ?
Do not test if `Meteor.role() === undefined`, it will return the **role object** or **null** but never **undefined**.

**Comment by hassanasad** [comment]
Just tested it. It initially returns `null` and then after little time, sends back an `object`.

Perhaps there is an issue with flow-router ? It has a method called `subscriptions` . Maybe we need to tell it explicitly which `subscriptions` to use for that action

**Comment by hassanasad** [comment]
Seems like Flow-router documentation also confirms your statement (to create a login link or error message in template layer)
https://kadira.io/academy/meteor-routing-guide/content/implementing-auth-logic-and-permissions

However, that seems a lot of work if all dashboard templates have to be protected this way.

**Comment by jalik** [comment]
@hassanasad have you finally resolved your problem ?
