### ISSUE TITLE
getUserRole

### ISSUE THREAD

**Issue by hassanasad** [jalik/jalik-roles#2]
Hi Jalik,

You have a nice helper function Role.setUserRole

Can you please make one Role.getUserRole( user_id ) so that role object for that particular user can be returned.

Thanks

**Comment by jalik** [comment]
I could do it but only for server, that's what you want ?

**Comment by jalik** [comment]
I added it in the v0.1.4.

**Comment by hassanasad** [comment]
Yeah for server side is fine.

However, can you please return the role object so that we can get role name too (instead of just the roleId)

**Comment by hassanasad** [comment]
Basically, we want to get the Role "Name" for each user that we list.

Perhaps you can help in that?

**Comment by jalik** [comment]
You don't even need the `Roles.getUserRole()` for that.
You can load all roles on client :

``` js
Meteor.subscribe('users');
Meteor.subscribe('roles');
```

Then list the users in a template :

``` html
<template name="users">
    {{#each users}}
        {{> usersItem}}
    {{/each}}
</template>

<template name="usersItem">
    <li>{{user.username}} has role {{role.name}}</li>
</template>
```

And finally create a helper to get the role of each user :

``` js
Template.users.helpers({
    users: function() {
        return Meteor.users.find();
    }
});
Template.usersItem.helpers({
    role: function() {
        return Meteor.roles.findOne(this.roleId);
    }
});
```

**Comment by hassanasad** [comment]
Okay. Thanks for the code example.

However, its not working for me.

`this.roleId` in your userItems helper comes out to be `undefined`

Also i think it should be `Meteor.roles.findOne({_id: this.roleId});` ?

**Comment by hassanasad** [comment]
Sorry - its working fine now.

I just wanted to have an easier method for this. Anyways, this will work too.

Thank you for you continued support

**Comment by hassanasad** [comment]
Hi Jalik can we have a template helper with which we can check users for their roles (and not just the logged in user).

Something like:

``` javascript
{{#if userCan 'administrate'}}
    <span class="label label-danger">{{role.name}}</span>
{{else}}
    <span class="label label-info">{{role.name}}</span>
{{/if}}
```

Where userCan is checked for the user in loop.

I want to apply different labels for Admin and Member

**Comment by jalik** [comment]
Hi @hassanasad, 
You can create your own template helper that will use the **this** as an User in the loop :

``` js
// As userCan helper already exists but concerns only the current user,
// we use another name for that helper.
Template.registerHelper('thisUserCan', function(permission) {
    var user = this;
    var roleId = user.roleId;
    return Roles.roleCan(permission, roleId);
});
// Be sure to return the roleId field in the publication
Meteor.publish('users', function() {
    return Meteor.users.find({}, {fields: {roleId: 1}});
});
```

I havn't tested it, but it should work.

**Comment by hassanasad** [comment]
Thanks Jalik, works like a charm :)
